AllCops:
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/PredicateName:
  Enabled: false
